<?php
return [
    'NO_RECORD_FOUND' => 'No record found',
    'SHIPPING_COUNTRY' => 'INDIA',
    'payu' => [
        'PAYMENT_URL' =>  'https://test.payu.in/_payment',
        'PAYMENT_SUCCESS_URL' => 'payment-response',
        'PAYMENT_FAILED_URL' => 'payment-response',
        'PAYMENT_CANCEL_URL' => 'payment-response',
        'PAYMENT_VERIFICATION_URL' => "https://test.payu.in/merchant/postservice.php?form=2",
        'PAYMENT_SUCCESS' => 'Success'
    ],
    // Do not change this payu_status
    'payu_status' => [
        'SUCCESS' => 'success',
        'FAILED' => 'failure',
    ],
    'payment_options' => [
        'ONLINE' => 'ONLINE',
        'PAYPAL' => 'PAYPAL',
        'RAZORPAY' => 'RAZORPAY',
        // 'COD' => 'COD',
    ],
    'cod_payment_options' => false,
    'order_status_codes' => [
        'PENDING' => 'PENDING',
        'PLACED' => 'PLACED',
        'PROCESSING' => 'PROCESSING',
        'SHIPPED' => 'SHIPPED',
        'DELIVERED' => 'DELIVERED',
        'CANCELLED' => 'CANCELLED',
        'FAILED' => 'FAILED',
        'RETURN_REQUESTED' => 'RETURN_REQUESTED',
        'RETURN_APPROVED' => 'RETURN_APPROVED',
        'RETURN_REJECTED' => 'RETURN_REJECTED',
        'RETURN_CANCELLED' => 'RETURN_CANCELLED',
        'REFUND_INITIATED' => 'REFUND_INITIATED',
        'REFUND_COMPLETED' => 'REFUND_COMPLETED',
        'REFUND_FAILED' => 'REFUND_FAILED',
    ],
    // 'order_status' => [
    //     'PENDING' => 'PENDING',
    //     'PLACED' => 'PLACED',
    //     'PROCESSING' => 'PROCESSING',
    //     'SHIPPED' => 'SHIPPED',
    //     'DELIVERED' => 'DELIVERED',
    //     'CANCELLED' => 'CANCELLED',
    //     'FAILED' => 'FAILED',
    //     'RETURN_REQUESTED' => 'RETURN_REQUESTED',
    //     'RETURN_APPROVED' => 'RETURN_APPROVED',
    // 'order_status' => [
    //     'PENDING' => 'PENDING',
    //     'PLACED' => 'PLACED',
    //     'PROCESSING' => 'PROCESSING',
    //     'SHIPPED' => 'SHIPPED',
    //     'DELIVERED' => 'DELIVERED',
    //     'CANCELLED' => 'CANCELLED',
    //     'FAILED' => 'FAILED',
    //     'RETURN_REQUESTED' => 'RETURN_REQUESTED',
    //     'RETURN_APPROVED' => 'RETURN_APPROVED',
    //     'RETURN_REJECTED' => 'RETURN_REJECTED',
    //     'RETURN_CANCELLED' => 'RETURN_CANCELLED',
    //     'REFUND_INITIATED' => 'REFUND_INITIATED',
    //     'REFUND_COMPLETED' => 'REFUND_COMPLETED',
    //     'REFUND_FAILED' => 'REFUND_FAILED',
    // ],
    'order_status_text' => [
        'PENDING' => 'PENDING',
        'PLACED' => 'PLACED',
        'PROCESSING' => 'PROCESSING',
        'SHIPPED' => 'SHIPPED',
        'DELIVERED' => 'DELIVERED',
        'CANCELLED' => 'CANCELLED',
        'FAILED' => 'FAILED',
        'RETURN_REQUESTED' => 'RETURN REQUESTED',
        'RETURN_APPROVED' => 'RETURN APPROVED',
        'RETURN_REJECTED' => 'RETURN REJECTED',
        'RETURN_CANCELLED' => 'RETURN CANCELLED',
        'REFUND_INITIATED' => 'REFUND INITIATED',
        'REFUND_COMPLETED' => 'REFUND COMPLETED',
        'REFUND_FAILED' => 'REFUND FAILED',
    ],
    'payment_status_codes' => [
        'PENDING' => 'PENDING',
        'INITIATED' => 'INITIATED',
        'COMPLETED' => 'COMPLETED',
        'FAILED' => 'FAILED',
    ],
    // 'payment_status' => [
    //     'PENDING' => 'PENDING',
    //     'INITIATED' => 'INITIATED',
    //     'COMPLETED' => 'COMPLETED',
    //     'FAILED' => 'FAILED'
    // ],
    // 'status_wise_bg_color' => [
    //     'SUCCESS' => 'bg-default',
    //     'FAILURE' => 'bg-secondary',
    //     'PENDING' => 'bg-primary',
    //     'INITIATED' => 'bg-primary',
    //     'PLACED' => 'bg-primary',
    //     'PROCESSING' => 'bg-warning',
    //     'COMPLETED' => 'bg-success',
    //     'FAILED' => 'bg-danger',
    //     'CANCELLED' => 'bg-danger',
    //     'RETURN_REQUESTED' => 'bg-primary',
    //     'RETURN_APPROVED' => 'bg-success',
    //     'RETURN_REJECTED' => 'bg-danger',
    //     'RETURN_CANCELLED' => 'bg-danger',
    //     'REFUND_INITIATED' => 'bg-primary',
    //     'REFUND_COMPLETED' => 'bg-success',
    //     'REFUND_FAILED' => 'bg-danger',
    // ],
    // 'payment_status_wise_bg_color' => [
    //     'PENDING' => 'bg-default',
    //     'INITIATED' => 'bg-primary',
    //     'COMPLETED' => 'bg-success',
    //     'FAILED' => 'bg-danger',
    // ],
    'website_contact_details' => [
        'support_email' => 'support@artificialgehna.com',
        'support_contact' => '+91-8076496831',
        'mail_address' => 'New Delhi, India',
        'address' => 'A-122, Street No. 6, Vijay Nagar, Mohan Garden, New Delhi, India',
    ],
    'social_media_links' => [
        'facebook' => 'https://www.facebook.com/theartificialgehna',
        'instagram' => 'https://www.instagram.com/artificialgehna/',
        'twitter' => '#',
        'linkedin' => '#',
    ],
    'stock_availability' => [
        1 => 'Available',
        0 => 'Out of stock',
    ],
    'sort_by_filter' => [
        'SORT_POPULARITY' => 'Sort by popularity',
        'SORT_LATEST' => 'Sort by latest',
        'PRICE_LOW_TO_HIGH' => 'Price low to high',
        'PRICE_HIGH_TO_LOW' => 'Price high to low',
    ],
    'product_listing_type' => [
        4 => 'Sale',
        1 => 'Trending',
        2 => 'Best Sellings',
        3 => 'Most Viewed',
    ],
    'filter_by_type' => [
        'SALE' => 'Sale',
        'TRENDING' => 'Trending',
        'BEST_SELLINGS' => 'Best Sellings',
        'MOST_VIEWED' => 'Most Viewed',
    ],
    'filter_by_type_code' => [
        'SALE' => 4,
        'TRENDING' => 1,
        'BEST_SELLINGS' => 2,
        'MOST_VIEWED' => 3,
    ],
    'filter_by_type_text' => [
        4 => 'SALE',
        1 => 'TRENDING',
        2 => 'BEST_SELLINGS',
        3 => 'MOST_VIEWED',
    ],
    'warehouse_address' => [
        'warehouse_first_name' => 'Manjeet',
        'warehouse_last_name' => 'Chauhan',
        'warehouse_address' => 'Shop No. 33, Our of plot no. 122 to 126, Vijay Vihar',
        'warehouse_address_2' => 'Mohan Garden, Uttam Nagar',
        'warehouse_city' => 'New Delhi',
        'warehouse_country' => 'India',
        'warehouse_pincode' => '110059',
        'warehouse_state' => 'Delhi',
        'warehouse_email' => 'support@artificialgehna.com',
        'warehouse_phone' => '7011751918',
    ],
    'shipping_charges' => env('SHIPPING_CHARGES', 0),
    'tax_percentage' => env('TAX_PERCENTAGE', 0)
];
